package MainClasses;

import Details.*;
import Details.TeacherAcademicInfo;
import java.security.SecureRandom;

public class Teacher extends User implements TeacherFunctions {
    TeacherAcademicInfo teacherAcademicInfo;

    // Constructor
    public Teacher(){}
    public Teacher(PersonalInfo personalInfo, ContactInfo contactInfo, Credentials Credentials, TeacherAcademicInfo teacherAcademicInfo) {
        super(personalInfo, contactInfo, Credentials);
        setTeacherAcademicInfo(teacherAcademicInfo);
    }

    // Getters
    public TeacherAcademicInfo getTeacherAcademicInfo() {
        return teacherAcademicInfo;
    }

    // Setters
    public void setTeacherAcademicInfo(TeacherAcademicInfo teacherAcademicInfo) {
        this.teacherAcademicInfo = teacherAcademicInfo;
    }

    // toString
    @Override
    public String toString() {
        return super.toString() + "\n " + getTeacherAcademicInfo();
    }
    public boolean isCredentialsMatched(Credentials credentials){
        return true; //temporary
    }
    public void uploadStudentAttendance(){

    }
    public void uploadStudentGrade(){
    }

    /**
     * Generates a username and secure password for a teacher.
     * <p>
     * The username is generated by combining the teacher's name (with spaces removed and converted to lowercase)
     * and a random 5-digit number. The password is a randomly generated secure 9-digit number.
     *
     * @return a {@link Credentials} object containing the generated username and password
     */
    public Credentials generateTeacherCredentials() {
        Credentials credentials = new Credentials();
        SecureRandom secureRandom = new SecureRandom();
        credentials.setUsername(this.getPersonalInfo().getName().replaceAll("\\s+", "").toLowerCase() + (10000 + secureRandom.nextInt(90000)));
        int random8Digit = 100000000 + secureRandom.nextInt(900000000);
        // Convert int to String
        credentials.setPassword(String.valueOf(random8Digit));
        return credentials;
    }
}
